/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-studio/backend/domain/rbac/internal/dal/model"
)

func newRbacUserRole(db *gorm.DB, opts ...gen.DOOption) rbacUserRole {
	_rbacUserRole := rbacUserRole{}

	_rbacUserRole.rbacUserRoleDo.UseDB(db, opts...)
	_rbacUserRole.rbacUserRoleDo.UseModel(&model.RbacUserRole{})

	tableName := _rbacUserRole.rbacUserRoleDo.TableName()
	_rbacUserRole.ALL = field.NewAsterisk(tableName)
	_rbacUserRole.ID = field.NewInt64(tableName, "id")
	_rbacUserRole.SpaceID = field.NewInt64(tableName, "space_id")
	_rbacUserRole.UserID = field.NewInt64(tableName, "user_id")
	_rbacUserRole.RoleID = field.NewInt64(tableName, "role_id")
	_rbacUserRole.AssignedBy = field.NewInt64(tableName, "assigned_by")
	_rbacUserRole.CreatedAt = field.NewInt64(tableName, "created_at")

	_rbacUserRole.fillFieldMap()

	return _rbacUserRole
}

// rbacUserRole User Role Assignment Table
type rbacUserRole struct {
	rbacUserRoleDo

	ALL        field.Asterisk
	ID         field.Int64 // ID
	SpaceID    field.Int64 // Space ID
	UserID     field.Int64 // User ID
	RoleID     field.Int64 // Role ID
	AssignedBy field.Int64 // Assigned By User ID
	CreatedAt  field.Int64 // Creation Time (Milliseconds)

	fieldMap map[string]field.Expr
}

func (r rbacUserRole) Table(newTableName string) *rbacUserRole {
	r.rbacUserRoleDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rbacUserRole) As(alias string) *rbacUserRole {
	r.rbacUserRoleDo.DO = *(r.rbacUserRoleDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rbacUserRole) updateTableName(table string) *rbacUserRole {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.SpaceID = field.NewInt64(table, "space_id")
	r.UserID = field.NewInt64(table, "user_id")
	r.RoleID = field.NewInt64(table, "role_id")
	r.AssignedBy = field.NewInt64(table, "assigned_by")
	r.CreatedAt = field.NewInt64(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *rbacUserRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rbacUserRole) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["space_id"] = r.SpaceID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["assigned_by"] = r.AssignedBy
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r rbacUserRole) clone(db *gorm.DB) rbacUserRole {
	r.rbacUserRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rbacUserRole) replaceDB(db *gorm.DB) rbacUserRole {
	r.rbacUserRoleDo.ReplaceDB(db)
	return r
}

type rbacUserRoleDo struct{ gen.DO }

type IRbacUserRoleDo interface {
	gen.SubQuery
	Debug() IRbacUserRoleDo
	WithContext(ctx context.Context) IRbacUserRoleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRbacUserRoleDo
	WriteDB() IRbacUserRoleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRbacUserRoleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRbacUserRoleDo
	Not(conds ...gen.Condition) IRbacUserRoleDo
	Or(conds ...gen.Condition) IRbacUserRoleDo
	Select(conds ...field.Expr) IRbacUserRoleDo
	Where(conds ...gen.Condition) IRbacUserRoleDo
	Order(conds ...field.Expr) IRbacUserRoleDo
	Distinct(cols ...field.Expr) IRbacUserRoleDo
	Omit(cols ...field.Expr) IRbacUserRoleDo
	Join(table schema.Tabler, on ...field.Expr) IRbacUserRoleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRbacUserRoleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRbacUserRoleDo
	Group(cols ...field.Expr) IRbacUserRoleDo
	Having(conds ...gen.Condition) IRbacUserRoleDo
	Limit(limit int) IRbacUserRoleDo
	Offset(offset int) IRbacUserRoleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRbacUserRoleDo
	Unscoped() IRbacUserRoleDo
	Create(values ...*model.RbacUserRole) error
	CreateInBatches(values []*model.RbacUserRole, batchSize int) error
	Save(values ...*model.RbacUserRole) error
	First() (*model.RbacUserRole, error)
	Take() (*model.RbacUserRole, error)
	Last() (*model.RbacUserRole, error)
	Find() ([]*model.RbacUserRole, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RbacUserRole, err error)
	FindInBatches(result *[]*model.RbacUserRole, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RbacUserRole) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRbacUserRoleDo
	Assign(attrs ...field.AssignExpr) IRbacUserRoleDo
	Joins(fields ...field.RelationField) IRbacUserRoleDo
	Preload(fields ...field.RelationField) IRbacUserRoleDo
	FirstOrInit() (*model.RbacUserRole, error)
	FirstOrCreate() (*model.RbacUserRole, error)
	FindByPage(offset int, limit int) (result []*model.RbacUserRole, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRbacUserRoleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rbacUserRoleDo) Debug() IRbacUserRoleDo {
	return r.withDO(r.DO.Debug())
}

func (r rbacUserRoleDo) WithContext(ctx context.Context) IRbacUserRoleDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rbacUserRoleDo) ReadDB() IRbacUserRoleDo {
	return r.Clauses(dbresolver.Read)
}

func (r rbacUserRoleDo) WriteDB() IRbacUserRoleDo {
	return r.Clauses(dbresolver.Write)
}

func (r rbacUserRoleDo) Session(config *gorm.Session) IRbacUserRoleDo {
	return r.withDO(r.DO.Session(config))
}

func (r rbacUserRoleDo) Clauses(conds ...clause.Expression) IRbacUserRoleDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rbacUserRoleDo) Returning(value interface{}, columns ...string) IRbacUserRoleDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rbacUserRoleDo) Not(conds ...gen.Condition) IRbacUserRoleDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rbacUserRoleDo) Or(conds ...gen.Condition) IRbacUserRoleDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rbacUserRoleDo) Select(conds ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rbacUserRoleDo) Where(conds ...gen.Condition) IRbacUserRoleDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rbacUserRoleDo) Order(conds ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rbacUserRoleDo) Distinct(cols ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rbacUserRoleDo) Omit(cols ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rbacUserRoleDo) Join(table schema.Tabler, on ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rbacUserRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rbacUserRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rbacUserRoleDo) Group(cols ...field.Expr) IRbacUserRoleDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rbacUserRoleDo) Having(conds ...gen.Condition) IRbacUserRoleDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rbacUserRoleDo) Limit(limit int) IRbacUserRoleDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rbacUserRoleDo) Offset(offset int) IRbacUserRoleDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rbacUserRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRbacUserRoleDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rbacUserRoleDo) Unscoped() IRbacUserRoleDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rbacUserRoleDo) Create(values ...*model.RbacUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rbacUserRoleDo) CreateInBatches(values []*model.RbacUserRole, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rbacUserRoleDo) Save(values ...*model.RbacUserRole) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rbacUserRoleDo) First() (*model.RbacUserRole, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacUserRole), nil
	}
}

func (r rbacUserRoleDo) Take() (*model.RbacUserRole, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacUserRole), nil
	}
}

func (r rbacUserRoleDo) Last() (*model.RbacUserRole, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacUserRole), nil
	}
}

func (r rbacUserRoleDo) Find() ([]*model.RbacUserRole, error) {
	result, err := r.DO.Find()
	return result.([]*model.RbacUserRole), err
}

func (r rbacUserRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RbacUserRole, err error) {
	buf := make([]*model.RbacUserRole, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rbacUserRoleDo) FindInBatches(result *[]*model.RbacUserRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rbacUserRoleDo) Attrs(attrs ...field.AssignExpr) IRbacUserRoleDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rbacUserRoleDo) Assign(attrs ...field.AssignExpr) IRbacUserRoleDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rbacUserRoleDo) Joins(fields ...field.RelationField) IRbacUserRoleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rbacUserRoleDo) Preload(fields ...field.RelationField) IRbacUserRoleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rbacUserRoleDo) FirstOrInit() (*model.RbacUserRole, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacUserRole), nil
	}
}

func (r rbacUserRoleDo) FirstOrCreate() (*model.RbacUserRole, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacUserRole), nil
	}
}

func (r rbacUserRoleDo) FindByPage(offset int, limit int) (result []*model.RbacUserRole, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rbacUserRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rbacUserRoleDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rbacUserRoleDo) Delete(models ...*model.RbacUserRole) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rbacUserRoleDo) withDO(do gen.Dao) *rbacUserRoleDo {
	r.DO = *do.(*gen.DO)
	return r
}
