/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-studio/backend/domain/rbac/internal/dal/model"
)

func newRbacRoleResourcePermission(db *gorm.DB, opts ...gen.DOOption) rbacRoleResourcePermission {
	_rbacRoleResourcePermission := rbacRoleResourcePermission{}

	_rbacRoleResourcePermission.rbacRoleResourcePermissionDo.UseDB(db, opts...)
	_rbacRoleResourcePermission.rbacRoleResourcePermissionDo.UseModel(&model.RbacRoleResourcePermission{})

	tableName := _rbacRoleResourcePermission.rbacRoleResourcePermissionDo.TableName()
	_rbacRoleResourcePermission.ALL = field.NewAsterisk(tableName)
	_rbacRoleResourcePermission.ID = field.NewInt64(tableName, "id")
	_rbacRoleResourcePermission.RoleID = field.NewInt64(tableName, "role_id")
	_rbacRoleResourcePermission.ResourceType = field.NewInt32(tableName, "resource_type")
	_rbacRoleResourcePermission.ResourceID = field.NewInt64(tableName, "resource_id")
	_rbacRoleResourcePermission.Actions = field.NewField(tableName, "actions")
	_rbacRoleResourcePermission.CreatedAt = field.NewInt64(tableName, "created_at")
	_rbacRoleResourcePermission.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_rbacRoleResourcePermission.fillFieldMap()

	return _rbacRoleResourcePermission
}

// rbacRoleResourcePermission Role Resource Permission Table
type rbacRoleResourcePermission struct {
	rbacRoleResourcePermissionDo

	ALL          field.Asterisk
	ID           field.Int64 // ID
	RoleID       field.Int64 // Role ID
	ResourceType field.Int32 // Resource Type: 4=agent, 6=workflow, 7=knowledge, 5=plugin, 23=database
	ResourceID   field.Int64 // Resource ID, 0 means all resources of this type
	Actions      field.Field // Action Array: ["create", "read", "update", "delete", "execute", "publish", "manage", "query", "install"]
	CreatedAt    field.Int64 // Creation Time (Milliseconds)
	UpdatedAt    field.Int64 // Update Time (Milliseconds)

	fieldMap map[string]field.Expr
}

func (r rbacRoleResourcePermission) Table(newTableName string) *rbacRoleResourcePermission {
	r.rbacRoleResourcePermissionDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rbacRoleResourcePermission) As(alias string) *rbacRoleResourcePermission {
	r.rbacRoleResourcePermissionDo.DO = *(r.rbacRoleResourcePermissionDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rbacRoleResourcePermission) updateTableName(table string) *rbacRoleResourcePermission {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.RoleID = field.NewInt64(table, "role_id")
	r.ResourceType = field.NewInt32(table, "resource_type")
	r.ResourceID = field.NewInt64(table, "resource_id")
	r.Actions = field.NewField(table, "actions")
	r.CreatedAt = field.NewInt64(table, "created_at")
	r.UpdatedAt = field.NewInt64(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *rbacRoleResourcePermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rbacRoleResourcePermission) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["resource_type"] = r.ResourceType
	r.fieldMap["resource_id"] = r.ResourceID
	r.fieldMap["actions"] = r.Actions
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r rbacRoleResourcePermission) clone(db *gorm.DB) rbacRoleResourcePermission {
	r.rbacRoleResourcePermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rbacRoleResourcePermission) replaceDB(db *gorm.DB) rbacRoleResourcePermission {
	r.rbacRoleResourcePermissionDo.ReplaceDB(db)
	return r
}

type rbacRoleResourcePermissionDo struct{ gen.DO }

type IRbacRoleResourcePermissionDo interface {
	gen.SubQuery
	Debug() IRbacRoleResourcePermissionDo
	WithContext(ctx context.Context) IRbacRoleResourcePermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRbacRoleResourcePermissionDo
	WriteDB() IRbacRoleResourcePermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRbacRoleResourcePermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRbacRoleResourcePermissionDo
	Not(conds ...gen.Condition) IRbacRoleResourcePermissionDo
	Or(conds ...gen.Condition) IRbacRoleResourcePermissionDo
	Select(conds ...field.Expr) IRbacRoleResourcePermissionDo
	Where(conds ...gen.Condition) IRbacRoleResourcePermissionDo
	Order(conds ...field.Expr) IRbacRoleResourcePermissionDo
	Distinct(cols ...field.Expr) IRbacRoleResourcePermissionDo
	Omit(cols ...field.Expr) IRbacRoleResourcePermissionDo
	Join(table schema.Tabler, on ...field.Expr) IRbacRoleResourcePermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRbacRoleResourcePermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRbacRoleResourcePermissionDo
	Group(cols ...field.Expr) IRbacRoleResourcePermissionDo
	Having(conds ...gen.Condition) IRbacRoleResourcePermissionDo
	Limit(limit int) IRbacRoleResourcePermissionDo
	Offset(offset int) IRbacRoleResourcePermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRbacRoleResourcePermissionDo
	Unscoped() IRbacRoleResourcePermissionDo
	Create(values ...*model.RbacRoleResourcePermission) error
	CreateInBatches(values []*model.RbacRoleResourcePermission, batchSize int) error
	Save(values ...*model.RbacRoleResourcePermission) error
	First() (*model.RbacRoleResourcePermission, error)
	Take() (*model.RbacRoleResourcePermission, error)
	Last() (*model.RbacRoleResourcePermission, error)
	Find() ([]*model.RbacRoleResourcePermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RbacRoleResourcePermission, err error)
	FindInBatches(result *[]*model.RbacRoleResourcePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RbacRoleResourcePermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRbacRoleResourcePermissionDo
	Assign(attrs ...field.AssignExpr) IRbacRoleResourcePermissionDo
	Joins(fields ...field.RelationField) IRbacRoleResourcePermissionDo
	Preload(fields ...field.RelationField) IRbacRoleResourcePermissionDo
	FirstOrInit() (*model.RbacRoleResourcePermission, error)
	FirstOrCreate() (*model.RbacRoleResourcePermission, error)
	FindByPage(offset int, limit int) (result []*model.RbacRoleResourcePermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRbacRoleResourcePermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rbacRoleResourcePermissionDo) Debug() IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Debug())
}

func (r rbacRoleResourcePermissionDo) WithContext(ctx context.Context) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rbacRoleResourcePermissionDo) ReadDB() IRbacRoleResourcePermissionDo {
	return r.Clauses(dbresolver.Read)
}

func (r rbacRoleResourcePermissionDo) WriteDB() IRbacRoleResourcePermissionDo {
	return r.Clauses(dbresolver.Write)
}

func (r rbacRoleResourcePermissionDo) Session(config *gorm.Session) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Session(config))
}

func (r rbacRoleResourcePermissionDo) Clauses(conds ...clause.Expression) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rbacRoleResourcePermissionDo) Returning(value interface{}, columns ...string) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rbacRoleResourcePermissionDo) Not(conds ...gen.Condition) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rbacRoleResourcePermissionDo) Or(conds ...gen.Condition) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rbacRoleResourcePermissionDo) Select(conds ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rbacRoleResourcePermissionDo) Where(conds ...gen.Condition) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rbacRoleResourcePermissionDo) Order(conds ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rbacRoleResourcePermissionDo) Distinct(cols ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rbacRoleResourcePermissionDo) Omit(cols ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rbacRoleResourcePermissionDo) Join(table schema.Tabler, on ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rbacRoleResourcePermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rbacRoleResourcePermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rbacRoleResourcePermissionDo) Group(cols ...field.Expr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rbacRoleResourcePermissionDo) Having(conds ...gen.Condition) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rbacRoleResourcePermissionDo) Limit(limit int) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rbacRoleResourcePermissionDo) Offset(offset int) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rbacRoleResourcePermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rbacRoleResourcePermissionDo) Unscoped() IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rbacRoleResourcePermissionDo) Create(values ...*model.RbacRoleResourcePermission) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rbacRoleResourcePermissionDo) CreateInBatches(values []*model.RbacRoleResourcePermission, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rbacRoleResourcePermissionDo) Save(values ...*model.RbacRoleResourcePermission) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rbacRoleResourcePermissionDo) First() (*model.RbacRoleResourcePermission, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRoleResourcePermission), nil
	}
}

func (r rbacRoleResourcePermissionDo) Take() (*model.RbacRoleResourcePermission, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRoleResourcePermission), nil
	}
}

func (r rbacRoleResourcePermissionDo) Last() (*model.RbacRoleResourcePermission, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRoleResourcePermission), nil
	}
}

func (r rbacRoleResourcePermissionDo) Find() ([]*model.RbacRoleResourcePermission, error) {
	result, err := r.DO.Find()
	return result.([]*model.RbacRoleResourcePermission), err
}

func (r rbacRoleResourcePermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RbacRoleResourcePermission, err error) {
	buf := make([]*model.RbacRoleResourcePermission, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rbacRoleResourcePermissionDo) FindInBatches(result *[]*model.RbacRoleResourcePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rbacRoleResourcePermissionDo) Attrs(attrs ...field.AssignExpr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rbacRoleResourcePermissionDo) Assign(attrs ...field.AssignExpr) IRbacRoleResourcePermissionDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rbacRoleResourcePermissionDo) Joins(fields ...field.RelationField) IRbacRoleResourcePermissionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rbacRoleResourcePermissionDo) Preload(fields ...field.RelationField) IRbacRoleResourcePermissionDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rbacRoleResourcePermissionDo) FirstOrInit() (*model.RbacRoleResourcePermission, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRoleResourcePermission), nil
	}
}

func (r rbacRoleResourcePermissionDo) FirstOrCreate() (*model.RbacRoleResourcePermission, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRoleResourcePermission), nil
	}
}

func (r rbacRoleResourcePermissionDo) FindByPage(offset int, limit int) (result []*model.RbacRoleResourcePermission, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rbacRoleResourcePermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rbacRoleResourcePermissionDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rbacRoleResourcePermissionDo) Delete(models ...*model.RbacRoleResourcePermission) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rbacRoleResourcePermissionDo) withDO(do gen.Dao) *rbacRoleResourcePermissionDo {
	r.DO = *do.(*gen.DO)
	return r
}
