/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-studio/backend/domain/rbac/internal/dal/model"
)

func newRbacRole(db *gorm.DB, opts ...gen.DOOption) rbacRole {
	_rbacRole := rbacRole{}

	_rbacRole.rbacRoleDo.UseDB(db, opts...)
	_rbacRole.rbacRoleDo.UseModel(&model.RbacRole{})

	tableName := _rbacRole.rbacRoleDo.TableName()
	_rbacRole.ALL = field.NewAsterisk(tableName)
	_rbacRole.ID = field.NewInt64(tableName, "id")
	_rbacRole.SpaceID = field.NewInt64(tableName, "space_id")
	_rbacRole.Name = field.NewString(tableName, "name")
	_rbacRole.Description = field.NewString(tableName, "description")
	_rbacRole.IsSystem = field.NewBool(tableName, "is_system")
	_rbacRole.CreatorID = field.NewInt64(tableName, "creator_id")
	_rbacRole.CreatedAt = field.NewInt64(tableName, "created_at")
	_rbacRole.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_rbacRole.DeletedAt = field.NewField(tableName, "deleted_at")

	_rbacRole.fillFieldMap()

	return _rbacRole
}

// rbacRole RBAC Custom Role Table
type rbacRole struct {
	rbacRoleDo

	ALL         field.Asterisk
	ID          field.Int64  // Role ID
	SpaceID     field.Int64  // Space ID
	Name        field.String // Role Name
	Description field.String // Role Description
	IsSystem    field.Bool   // Is System Role: 1=system predefined, 0=custom
	CreatorID   field.Int64  // Creator User ID
	CreatedAt   field.Int64  // Creation Time (Milliseconds)
	UpdatedAt   field.Int64  // Update Time (Milliseconds)
	DeletedAt   field.Field  // Deletion Time (Milliseconds)

	fieldMap map[string]field.Expr
}

func (r rbacRole) Table(newTableName string) *rbacRole {
	r.rbacRoleDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rbacRole) As(alias string) *rbacRole {
	r.rbacRoleDo.DO = *(r.rbacRoleDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rbacRole) updateTableName(table string) *rbacRole {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.SpaceID = field.NewInt64(table, "space_id")
	r.Name = field.NewString(table, "name")
	r.Description = field.NewString(table, "description")
	r.IsSystem = field.NewBool(table, "is_system")
	r.CreatorID = field.NewInt64(table, "creator_id")
	r.CreatedAt = field.NewInt64(table, "created_at")
	r.UpdatedAt = field.NewInt64(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *rbacRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rbacRole) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 9)
	r.fieldMap["id"] = r.ID
	r.fieldMap["space_id"] = r.SpaceID
	r.fieldMap["name"] = r.Name
	r.fieldMap["description"] = r.Description
	r.fieldMap["is_system"] = r.IsSystem
	r.fieldMap["creator_id"] = r.CreatorID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r rbacRole) clone(db *gorm.DB) rbacRole {
	r.rbacRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rbacRole) replaceDB(db *gorm.DB) rbacRole {
	r.rbacRoleDo.ReplaceDB(db)
	return r
}

type rbacRoleDo struct{ gen.DO }

type IRbacRoleDo interface {
	gen.SubQuery
	Debug() IRbacRoleDo
	WithContext(ctx context.Context) IRbacRoleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRbacRoleDo
	WriteDB() IRbacRoleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRbacRoleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRbacRoleDo
	Not(conds ...gen.Condition) IRbacRoleDo
	Or(conds ...gen.Condition) IRbacRoleDo
	Select(conds ...field.Expr) IRbacRoleDo
	Where(conds ...gen.Condition) IRbacRoleDo
	Order(conds ...field.Expr) IRbacRoleDo
	Distinct(cols ...field.Expr) IRbacRoleDo
	Omit(cols ...field.Expr) IRbacRoleDo
	Join(table schema.Tabler, on ...field.Expr) IRbacRoleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRbacRoleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRbacRoleDo
	Group(cols ...field.Expr) IRbacRoleDo
	Having(conds ...gen.Condition) IRbacRoleDo
	Limit(limit int) IRbacRoleDo
	Offset(offset int) IRbacRoleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRbacRoleDo
	Unscoped() IRbacRoleDo
	Create(values ...*model.RbacRole) error
	CreateInBatches(values []*model.RbacRole, batchSize int) error
	Save(values ...*model.RbacRole) error
	First() (*model.RbacRole, error)
	Take() (*model.RbacRole, error)
	Last() (*model.RbacRole, error)
	Find() ([]*model.RbacRole, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RbacRole, err error)
	FindInBatches(result *[]*model.RbacRole, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RbacRole) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRbacRoleDo
	Assign(attrs ...field.AssignExpr) IRbacRoleDo
	Joins(fields ...field.RelationField) IRbacRoleDo
	Preload(fields ...field.RelationField) IRbacRoleDo
	FirstOrInit() (*model.RbacRole, error)
	FirstOrCreate() (*model.RbacRole, error)
	FindByPage(offset int, limit int) (result []*model.RbacRole, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRbacRoleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rbacRoleDo) Debug() IRbacRoleDo {
	return r.withDO(r.DO.Debug())
}

func (r rbacRoleDo) WithContext(ctx context.Context) IRbacRoleDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rbacRoleDo) ReadDB() IRbacRoleDo {
	return r.Clauses(dbresolver.Read)
}

func (r rbacRoleDo) WriteDB() IRbacRoleDo {
	return r.Clauses(dbresolver.Write)
}

func (r rbacRoleDo) Session(config *gorm.Session) IRbacRoleDo {
	return r.withDO(r.DO.Session(config))
}

func (r rbacRoleDo) Clauses(conds ...clause.Expression) IRbacRoleDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rbacRoleDo) Returning(value interface{}, columns ...string) IRbacRoleDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rbacRoleDo) Not(conds ...gen.Condition) IRbacRoleDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rbacRoleDo) Or(conds ...gen.Condition) IRbacRoleDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rbacRoleDo) Select(conds ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rbacRoleDo) Where(conds ...gen.Condition) IRbacRoleDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rbacRoleDo) Order(conds ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rbacRoleDo) Distinct(cols ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rbacRoleDo) Omit(cols ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rbacRoleDo) Join(table schema.Tabler, on ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rbacRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rbacRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rbacRoleDo) Group(cols ...field.Expr) IRbacRoleDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rbacRoleDo) Having(conds ...gen.Condition) IRbacRoleDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rbacRoleDo) Limit(limit int) IRbacRoleDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rbacRoleDo) Offset(offset int) IRbacRoleDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rbacRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRbacRoleDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rbacRoleDo) Unscoped() IRbacRoleDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rbacRoleDo) Create(values ...*model.RbacRole) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rbacRoleDo) CreateInBatches(values []*model.RbacRole, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rbacRoleDo) Save(values ...*model.RbacRole) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rbacRoleDo) First() (*model.RbacRole, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRole), nil
	}
}

func (r rbacRoleDo) Take() (*model.RbacRole, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRole), nil
	}
}

func (r rbacRoleDo) Last() (*model.RbacRole, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRole), nil
	}
}

func (r rbacRoleDo) Find() ([]*model.RbacRole, error) {
	result, err := r.DO.Find()
	return result.([]*model.RbacRole), err
}

func (r rbacRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RbacRole, err error) {
	buf := make([]*model.RbacRole, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rbacRoleDo) FindInBatches(result *[]*model.RbacRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rbacRoleDo) Attrs(attrs ...field.AssignExpr) IRbacRoleDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rbacRoleDo) Assign(attrs ...field.AssignExpr) IRbacRoleDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rbacRoleDo) Joins(fields ...field.RelationField) IRbacRoleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rbacRoleDo) Preload(fields ...field.RelationField) IRbacRoleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rbacRoleDo) FirstOrInit() (*model.RbacRole, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRole), nil
	}
}

func (r rbacRoleDo) FirstOrCreate() (*model.RbacRole, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RbacRole), nil
	}
}

func (r rbacRoleDo) FindByPage(offset int, limit int) (result []*model.RbacRole, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rbacRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rbacRoleDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rbacRoleDo) Delete(models ...*model.RbacRole) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rbacRoleDo) withDO(do gen.Dao) *rbacRoleDo {
	r.DO = *do.(*gen.DO)
	return r
}
