/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRbacRole = "rbac_role"

// RbacRole RBAC Custom Role Table
type RbacRole struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Role ID" json:"id"`                                      // Role ID
	SpaceID     int64  `gorm:"column:space_id;not null;comment:Space ID" json:"space_id"`                                              // Space ID
	Name        string `gorm:"column:name;not null;comment:Role Name" json:"name"`                                                     // Role Name
	Description string `gorm:"column:description;not null;comment:Role Description" json:"description"`                                // Role Description
	IsSystem    bool   `gorm:"column:is_system;not null;comment:Is System Role: 1=system predefined, 0=custom" json:"is_system"`       // Is System Role: 1=system predefined, 0=custom
	CreatorID   int64  `gorm:"column:creator_id;not null;comment:Creator User ID" json:"creator_id"`                                   // Creator User ID
	CreatedAt   int64  `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Creation Time (Milliseconds)" json:"created_at"` // Creation Time (Milliseconds)
	UpdatedAt   int64  `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time (Milliseconds)" json:"updated_at"`   // Update Time (Milliseconds)
	DeletedAt   *int64 `gorm:"column:deleted_at;comment:Deletion Time (Milliseconds)" json:"deleted_at"`                               // Deletion Time (Milliseconds)
}

// TableName RbacRole's table name
func (*RbacRole) TableName() string {
	return TableNameRbacRole
}
