/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRbacUserRole = "rbac_user_role"

// RbacUserRole User Role Assignment Table
type RbacUserRole struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                           // ID
	SpaceID    int64 `gorm:"column:space_id;not null;comment:Space ID" json:"space_id"`                                              // Space ID
	UserID     int64 `gorm:"column:user_id;not null;comment:User ID" json:"user_id"`                                                 // User ID
	RoleID     int64 `gorm:"column:role_id;not null;comment:Role ID" json:"role_id"`                                                 // Role ID
	AssignedBy int64 `gorm:"column:assigned_by;not null;comment:Assigned By User ID" json:"assigned_by"`                             // Assigned By User ID
	CreatedAt  int64 `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Creation Time (Milliseconds)" json:"created_at"` // Creation Time (Milliseconds)
}

// TableName RbacUserRole's table name
func (*RbacUserRole) TableName() string {
	return TableNameRbacUserRole
}
