/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRbacUserResourcePermission = "rbac_user_resource_permission"

// RbacUserResourcePermission 用户资源权限表
type RbacUserResourcePermission struct {
	ID           int64       `gorm:"column:id;not null;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	UserID       string      `gorm:"column:user_id;not null;comment:User ID" json:"user_id"`
	SpaceID      int64       `gorm:"column:space_id;not null;comment:Space ID" json:"space_id"`
	ResourceType int         `gorm:"column:resource_type;not null;comment:Resource Type: 4=agent, 5=plugin, 6=workflow, 7=knowledge, 17=prompt, 23=database" json:"resource_type"`
	ResourceID   string      `gorm:"column:resource_id;not null;comment:Resource ID" json:"resource_id"`
	Actions      StringArray `gorm:"column:actions;not null;comment:Action Array" json:"actions"`
	CreatedAt    int64       `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Creation Time (Milliseconds)" json:"created_at"`
	UpdatedAt    int64       `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time (Milliseconds)" json:"updated_at"`
}

// TableName RbacUserResourcePermission's table name
func (*RbacUserResourcePermission) TableName() string {
	return TableNameRbacUserResourcePermission
}

