/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const TableNameRbacRoleResourcePermission = "rbac_role_resource_permission"

// StringArray 自定义类型，用于处理 JSON 数组
type StringArray []string

// Value 实现 driver.Valuer 接口
func (s StringArray) Value() (driver.Value, error) {
	if s == nil {
		return "[]", nil
	}
	b, err := json.Marshal(s)
	return string(b), err
}

// Scan 实现 sql.Scanner 接口
func (s *StringArray) Scan(value interface{}) error {
	if value == nil {
		*s = []string{}
		return nil
	}
	var bytes []byte
	switch v := value.(type) {
	case []byte:
		bytes = v
	case string:
		bytes = []byte(v)
	default:
		return fmt.Errorf("failed to scan StringArray: %v", value)
	}
	return json.Unmarshal(bytes, s)
}

// RbacRoleResourcePermission Role Resource Permission Table
type RbacRoleResourcePermission struct {
	ID           int64       `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                                                                   // ID
	RoleID       int64       `gorm:"column:role_id;not null;comment:Role ID" json:"role_id"`                                                                                         // Role ID
	ResourceType int32       `gorm:"column:resource_type;not null;comment:Resource Type: 4=agent, 6=workflow, 7=knowledge, 5=plugin, 23=database" json:"resource_type"`              // Resource Type: 4=agent, 6=workflow, 7=knowledge, 5=plugin, 23=database
	ResourceID   int64       `gorm:"column:resource_id;not null;comment:Resource ID, 0 means all resources of this type" json:"resource_id"`                                         // Resource ID, 0 means all resources of this type
	Actions      StringArray `gorm:"column:actions;type:json;not null;comment:Action Array: [\"create\", \"read\", \"update\", \"delete\", \"execute\", \"publish\"]" json:"actions"` // Action Array
	CreatedAt    int64       `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Creation Time (Milliseconds)" json:"created_at"`                                         // Creation Time (Milliseconds)
	UpdatedAt    int64       `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time (Milliseconds)" json:"updated_at"`                                           // Update Time (Milliseconds)
}

// TableName RbacRoleResourcePermission's table name
func (*RbacRoleResourcePermission) TableName() string {
	return TableNameRbacRoleResourcePermission
}
