/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameAppDynamicConversationOnline = "app_dynamic_conversation_online"

// AppDynamicConversationOnline app_dynamic_conversation_online
type AppDynamicConversationOnline struct {
	ID             int64          `gorm:"column:id;primaryKey;comment:id" json:"id"`                                                            // id
	AppID          int64          `gorm:"column:app_id;not null;comment:app id" json:"app_id"`                                                  // app id
	Name           string         `gorm:"column:name;not null;comment:conversation name" json:"name"`                                           // conversation name
	UserID         int64          `gorm:"column:user_id;not null;comment:user id" json:"user_id"`                                               // user id
	ConnectorID    int64          `gorm:"column:connector_id;not null;comment:connector id" json:"connector_id"`                                // connector id
	ConversationID int64          `gorm:"column:conversation_id;not null;comment:conversation id" json:"conversation_id"`                       // conversation id
	CreatedAt      int64          `gorm:"column:created_at;not null;autoCreateTime:milli;comment:create time in millisecond" json:"created_at"` // create time in millisecond
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment:delete time in millisecond" json:"deleted_at"`                               // delete time in millisecond
}

// TableName AppDynamicConversationOnline's table name
func (*AppDynamicConversationOnline) TableName() string {
	return TableNameAppDynamicConversationOnline
}
