/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConnectorWorkflowVersion = "connector_workflow_version"

// ConnectorWorkflowVersion connector workflow version
type ConnectorWorkflowVersion struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                                         // id
	AppID       int64  `gorm:"column:app_id;not null;comment:app id" json:"app_id"`                                                  // app id
	ConnectorID int64  `gorm:"column:connector_id;not null;comment:connector id" json:"connector_id"`                                // connector id
	WorkflowID  int64  `gorm:"column:workflow_id;not null;comment:workflow id" json:"workflow_id"`                                   // workflow id
	Version     string `gorm:"column:version;not null;comment:version" json:"version"`                                               // version
	CreatedAt   int64  `gorm:"column:created_at;not null;autoCreateTime:milli;comment:create time in millisecond" json:"created_at"` // create time in millisecond
}

// TableName ConnectorWorkflowVersion's table name
func (*ConnectorWorkflowVersion) TableName() string {
	return TableNameConnectorWorkflowVersion
}
