/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWorkflowSnapshot = "workflow_snapshot"

// WorkflowSnapshot snapshot for executed workflow draft
type WorkflowSnapshot struct {
	WorkflowID   int64  `gorm:"column:workflow_id;not null;comment:workflow id this snapshot belongs to" json:"workflow_id"`           // workflow id this snapshot belongs to
	CommitID     string `gorm:"column:commit_id;not null;comment:the commit id of the workflow draft" json:"commit_id"`                // the commit id of the workflow draft
	Canvas       string `gorm:"column:canvas;comment:frontend schema for this snapshot" json:"canvas"`                                 // frontend schema for this snapshot
	InputParams  string `gorm:"column:input_params;comment:input parameter info" json:"input_params"`                                  // input parameter info
	OutputParams string `gorm:"column:output_params;comment:output parameter info" json:"output_params"`                               // output parameter info
	CreatedAt    int64  `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                          // ID
}

// TableName WorkflowSnapshot's table name
func (*WorkflowSnapshot) TableName() string {
	return TableNameWorkflowSnapshot
}
