/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/coze-dev/coze-studio/backend/api/model/admin/config"
	"github.com/coze-dev/coze-studio/backend/api/model/app/developer_api"
	"gorm.io/gorm"
)

const TableNameModelInstance = "model_instance"

// ModelInstance Model Instance Management Table
type ModelInstance struct {
	ID          int64                           `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                                          // id
	Type        int32                           `gorm:"column:type;not null;comment:Model Type 0-LLM 1-TextEmbedding 2-Rerank" json:"type"`                    // Model Type 0-LLM 1-TextEmbedding 2-Rerank
	Provider    *config.ModelProvider           `gorm:"column:provider;not null;comment:Provider Information;serializer:json" json:"provider"`                 // Provider Information
	DisplayInfo *config.DisplayInfo             `gorm:"column:display_info;not null;comment:Display Information;serializer:json" json:"display_info"`          // Display Information
	Connection  *config.Connection              `gorm:"column:connection;not null;comment:Connection Information;serializer:json" json:"connection"`           // Connection Information
	Capability  *developer_api.ModelAbility     `gorm:"column:capability;not null;comment:Model Capability;serializer:json" json:"capability"`                 // Model Capability
	Parameters  []*developer_api.ModelParameter `gorm:"column:parameters;not null;comment:Model Parameters;serializer:json" json:"parameters"`                 // Model Parameters
	Extra       string                          `gorm:"column:extra;comment:Extra Information" json:"extra"`                                                   // Extra Information
	CreatedAt   int64                           `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt   int64                           `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt   gorm.DeletedAt                  `gorm:"column:deleted_at;comment:Delete Time" json:"deleted_at"`                                               // Delete Time
}

// TableName ModelInstance's table name
func (*ModelInstance) TableName() string {
	return TableNameModelInstance
}
